name: build-wind4
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - name: restore
      working-directory: ${{github.workspace}}
      shell: cmd
      run: nuget restore Wind4Config.sln -LockedMode

    - name: build
      working-directory: ${{github.workspace}}
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
        devenv Wind4Config.sln /Rebuild Release

    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: Wind4Config
        path: bin\Wind4Config\Release\net35\